sonar.projectKey=KalaimaranB_BioPro
sonar.organization=kalaimaranb
sonar.projectName=BioPro
sonar.python.version=3.12
sonar.sources=biopro
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.cpd.exclusions=tests/**
sonar.coverage.exclusions=tests/**
