sonar.projectKey=KalaimaranB_BioPro
sonar.organization=kalaimaranb
sonar.projectName=BioPro
sonar.python.version=3.10
sonar.sources=biopro
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8
